Update:  menu added
MortezaBashsiz/nipovpnbash pull request #6
Opened 2022-11-21 20:12 UTC by alimehr75

In order to prevent any mistakes, a menu of VPN Services has been Created in nipovpn.sh :
1. Users can select VPN Services by just a number 
2. There is no need to type the exact Service name 

Changes: 
1. list of services added
2. `select` _VPN_SERVICE in provided list 
3. `break` added to each choice
4. `Quit` added in menu

2022-11-22 10:20 UTC, MortezaBashsiz commented on scripts/nipovpn.sh
> +# ---------- Select service with number (There is no need to type) ------
Thanks
No need to comment the weakness of the code :D

2022-11-22 10:24 UTC, MortezaBashsiz commented on scripts/nipovpn.sh
> +PS3="Choose Your Desired Service: "
Please use the variable name like _NAME_VAR

2022-11-22 10:25 UTC, MortezaBashsiz commented on scripts/nipovpn.sh
> +VPNS=("shadowsocks+obfs" "v2ray+vmess" "v2ray+vmess+ws" "trojan" "Quit")
There also is a variable named _VPN_SERVICE_LIST in interaction.sh
You can use this

2022-11-22 10:27 UTC, MortezaBashsiz requested changes
Hi
Thank you so much for contribution
I tried to comment on your changes
I will wait for your changes

2022-11-26 06:55 UTC, alimehr75 commented on scripts/nipovpn.sh
> +# ---------- Select service with number (There is no need to type) ------
no, it's my habit to comment on everything to clarifying

2022-11-26 14:29 UTC, alimehr75 reviewed
Update with existing lists , minor changes

2022-11-26 14:36 UTC, alimehr75 commented
I committed it wrong, I'm working on it tonight

2022-11-26 14:41 UTC, alimehr75 commented on scripts/nipovpn.sh
> +VPNS=("shadowsocks+obfs" "v2ray+vmess" "v2ray+vmess+ws" "trojan" "Quit")
okay ill use it 
thank you .

2022-11-26 15:33 UTC, alimehr75 commented on scripts/nipovpn.sh
> +PS3="Choose Your Desired Service: "
This `PS3` (Prompt string 3) is a prompt string instead of printing just like this:
`#?` for choices

2022-11-26 19:48 UTC, alimehr75 commented
The changes have been applied 
if its need other changes , let me know

2022-11-27 09:24 UTC, MortezaBashsiz reviewed
Done
Thanks for your contribution

2022-11-27 09:24 UTC, merged

2022-11-27 10:00 UTC, MortezaBashsiz commented
I had to revert the changes
You have to do the stuff in interraction.sh
Please change what ever you want and test the code completely
If it works? then create pull request
I missed this part
Sorry

2022-11-27 10:04 UTC, alimehr75 commented
okay 
i'll work on it 
Thank you.